// Version

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: modules/cart/cartPb/cartPb.proto

package bigdobshop_micro

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Structures
type FindCartsInIdsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *FindCartsInIdsReq) Reset() {
	*x = FindCartsInIdsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_cart_cartPb_cartPb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCartsInIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCartsInIdsReq) ProtoMessage() {}

func (x *FindCartsInIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_modules_cart_cartPb_cartPb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCartsInIdsReq.ProtoReflect.Descriptor instead.
func (*FindCartsInIdsReq) Descriptor() ([]byte, []int) {
	return file_modules_cart_cartPb_cartPb_proto_rawDescGZIP(), []int{0}
}

func (x *FindCartsInIdsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type FindCartsInIdsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carts []*Cart `protobuf:"bytes,1,rep,name=carts,proto3" json:"carts,omitempty"`
}

func (x *FindCartsInIdsRes) Reset() {
	*x = FindCartsInIdsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_cart_cartPb_cartPb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindCartsInIdsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindCartsInIdsRes) ProtoMessage() {}

func (x *FindCartsInIdsRes) ProtoReflect() protoreflect.Message {
	mi := &file_modules_cart_cartPb_cartPb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindCartsInIdsRes.ProtoReflect.Descriptor instead.
func (*FindCartsInIdsRes) Descriptor() ([]byte, []int) {
	return file_modules_cart_cartPb_cartPb_proto_rawDescGZIP(), []int{1}
}

func (x *FindCartsInIdsRes) GetCarts() []*Cart {
	if x != nil {
		return x.Carts
	}
	return nil
}

type Cart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price    float64 `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl string  `protobuf:"bytes,4,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (x *Cart) Reset() {
	*x = Cart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modules_cart_cartPb_cartPb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_modules_cart_cartPb_cartPb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_modules_cart_cartPb_cartPb_proto_rawDescGZIP(), []int{2}
}

func (x *Cart) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cart) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Cart) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Cart) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_modules_cart_cartPb_cartPb_proto protoreflect.FileDescriptor

var file_modules_cart_cartPb_cartPb_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x63,
	0x61, 0x72, 0x74, 0x50, 0x62, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x50, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x25, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x74, 0x73, 0x49,
	0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x30, 0x0a, 0x11, 0x46, 0x69, 0x6e,
	0x64, 0x43, 0x61, 0x72, 0x74, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1b,
	0x0a, 0x05, 0x63, 0x61, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x05, 0x63, 0x61, 0x72, 0x74, 0x73, 0x22, 0x5e, 0x0a, 0x04, 0x43,
	0x61, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x32, 0x4b, 0x0a, 0x0f, 0x43,
	0x61, 0x72, 0x74, 0x47, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x74, 0x73, 0x49, 0x6e, 0x49, 0x64, 0x73,
	0x12, 0x12, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x74, 0x73, 0x49, 0x6e, 0x49, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x74, 0x73,
	0x49, 0x6e, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x61, 0x6e, 0x74, 0x68, 0x61, 0x70, 0x68, 0x6f,
	0x6c, 0x32, 0x2f, 0x62, 0x69, 0x67, 0x64, 0x6f, 0x62, 0x73, 0x68, 0x6f, 0x70, 0x2d, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_modules_cart_cartPb_cartPb_proto_rawDescOnce sync.Once
	file_modules_cart_cartPb_cartPb_proto_rawDescData = file_modules_cart_cartPb_cartPb_proto_rawDesc
)

func file_modules_cart_cartPb_cartPb_proto_rawDescGZIP() []byte {
	file_modules_cart_cartPb_cartPb_proto_rawDescOnce.Do(func() {
		file_modules_cart_cartPb_cartPb_proto_rawDescData = protoimpl.X.CompressGZIP(file_modules_cart_cartPb_cartPb_proto_rawDescData)
	})
	return file_modules_cart_cartPb_cartPb_proto_rawDescData
}

var file_modules_cart_cartPb_cartPb_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_modules_cart_cartPb_cartPb_proto_goTypes = []interface{}{
	(*FindCartsInIdsReq)(nil), // 0: FindCartsInIdsReq
	(*FindCartsInIdsRes)(nil), // 1: FindCartsInIdsRes
	(*Cart)(nil),              // 2: Cart
}
var file_modules_cart_cartPb_cartPb_proto_depIdxs = []int32{
	2, // 0: FindCartsInIdsRes.carts:type_name -> Cart
	0, // 1: CartGrpcService.FindCartsInIds:input_type -> FindCartsInIdsReq
	1, // 2: CartGrpcService.FindCartsInIds:output_type -> FindCartsInIdsRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_modules_cart_cartPb_cartPb_proto_init() }
func file_modules_cart_cartPb_cartPb_proto_init() {
	if File_modules_cart_cartPb_cartPb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modules_cart_cartPb_cartPb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCartsInIdsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_cart_cartPb_cartPb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindCartsInIdsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modules_cart_cartPb_cartPb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modules_cart_cartPb_cartPb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_modules_cart_cartPb_cartPb_proto_goTypes,
		DependencyIndexes: file_modules_cart_cartPb_cartPb_proto_depIdxs,
		MessageInfos:      file_modules_cart_cartPb_cartPb_proto_msgTypes,
	}.Build()
	File_modules_cart_cartPb_cartPb_proto = out.File
	file_modules_cart_cartPb_cartPb_proto_rawDesc = nil
	file_modules_cart_cartPb_cartPb_proto_goTypes = nil
	file_modules_cart_cartPb_cartPb_proto_depIdxs = nil
}
